export const metadata = {
  title: "CreditPass — Whitepaper",
  description: "Cross-chain credit scoring via the Attestcoin Protocol. Verify Ethereum repayments on Creditcoin without oracles.",
};

export default function WhitepaperPage() {
  return (
    <div className="min-h-screen bg-paper-white text-ink-black">
      {/* Header */}
      <header className="border-b border-ink-black bg-ink-black text-paper-white">
        <div className="mx-auto flex max-w-[800px] items-center justify-between px-5 py-4">
          <a href="/" className="font-ui text-xl font-bold tracking-tight uppercase">
            CreditPass
          </a>
          <a
            href="/"
            className="font-ui text-sm uppercase tracking-[0.1em] px-4 py-2 pill-nav bg-eclipse-green text-ink-black hover:scale-105 transition-transform"
          >
            ← Back to App
          </a>
        </div>
      </header>

      {/* Content */}
      <main className="mx-auto max-w-[800px] px-5 py-16">
        {/* Title */}
        <div className="mb-16">
          <div className="eyebrow text-muted-foreground mb-4">Whitepaper · v1.1</div>
          <h1 className="font-heading text-5xl font-light leading-[0.9] tracking-[-0.03em]">
            CreditPass
          </h1>
          <h2 className="font-heading text-2xl font-light mt-2 text-muted-foreground">
            Cross-Chain Credit Passport
          </h2>
          <p className="mt-6 font-ui text-lg leading-relaxed">
            Your repayment history on Ethereum is your credit score on Creditcoin —
            verified cryptographically via the Attestcoin Protocol. No oracle, no intermediary, just math.
          </p>
        </div>

        {/* 1. Problem */}
        <section className="mb-14">
          <h3 className="font-heading text-3xl font-light mb-4">01 — The Problem</h3>
          <p className="font-ui text-base leading-relaxed mb-4">
            On-chain repayment history is trapped on the chain where it happened. A borrower with a
            perfect repayment record on Ethereum is invisible on Creditcoin — treated as a new
            borrower with no credit history, penalized with high interest rates and low borrowing limits.
          </p>
          <p className="font-ui text-base leading-relaxed">
            Traditional credit infrastructure relies on centralized credit bureaus and off-chain data.
            DeFi lending protocols rely on collateral ratios alone — they cannot assess repayment
            history across chains. Every chain is a silo. Every borrower starts from zero.
          </p>
        </section>

        {/* 2. Solution */}
        <section className="mb-14">
          <h3 className="font-heading text-3xl font-light mb-4">02 — The Solution</h3>
          <p className="font-ui text-base leading-relaxed mb-4">
            CreditPass uses the <strong>Attestcoin Protocol</strong> to cryptographically verify
            Sepolia loan repayment transactions on Creditcoin. A smart contract on Creditcoin verifies
            that a transaction occurred on Ethereum using only on-chain precompiles — no Chainlink,
            no off-chain oracle, no trusted intermediary.
          </p>
          <p className="font-ui text-base leading-relaxed">
            Verified repayments update the borrower's credit score on Creditcoin. A lending contract
            reads this score to determine interest rates and borrowing limits. Better repayment history
            on Ethereum means better loan terms on Creditcoin.
          </p>
        </section>

        {/* 3. Architecture */}
        <section className="mb-14">
          <h3 className="font-heading text-3xl font-light mb-4">03 — Architecture</h3>

          <div className="mb-6 p-6 pill border border-ink-black bg-ink-black text-paper-white">
            <div className="eyebrow text-eclipse-green mb-2">Source Chain — Ethereum Sepolia</div>
            <p className="font-ui text-sm leading-relaxed">
              <code className="font-label text-eclipse-green">LoanSource.sol</code> — A lending contract
              that records loan repayments. Emits <code className="font-label text-eclipse-green">Repayment(address borrower, uint256 amount, uint256 timestamp)</code> events.
              This is the contract whose transactions the Attestcoin Protocol verifies.
            </p>
          </div>

          <div className="mb-6 p-6 pill border border-ink-black bg-eclipse-green">
            <div className="eyebrow text-ink-black mb-2">Destination Chain — Creditcoin Testnet</div>
            <p className="font-ui text-sm leading-relaxed mb-3">
              <code className="font-label font-bold">CreditPass.sol</code> — The core contract. It:
            </p>
            <ol className="font-ui text-sm leading-relaxed space-y-1 ml-4">
              <li>1. Receives proof data (generated by USC SDK / proof builder API)</li>
              <li>2. Calls BlockProver precompile (<code className="font-label">0x...0FD2</code>) to verify the proof</li>
              <li>3. Calls ChainInfo precompile (<code className="font-label">0x...0fd3</code>) for chain validation</li>
              <li>4. Decodes the verified transaction data (borrower address, repayment amount)</li>
              <li>5. Updates the borrower's credit score (<code className="font-label">mapping: address → uint256</code>)</li>
              <li>6. Mints or updates the soulbound NFT passport via <code className="font-label">CreditPassNFT.mintOrUpdate()</code></li>
              <li>7. Supports batch verification for importing multiple repayments at once</li>
            </ol>
          </div>

          <div className="mb-6 p-6 pill border border-ink-black bg-paper-white">
            <div className="eyebrow text-muted-foreground mb-2">Lending — Creditcoin Testnet</div>
            <p className="font-ui text-sm leading-relaxed">
              <code className="font-label">CreditLender.sol</code> — A lending contract that reads the
              borrower's credit score from CreditPass, determines interest rate (lower score = higher rate)
              and max borrow amount, accepts CTC collateral, and issues loans in testnet tokens.
            </p>
          </div>

          <div className="mb-6 p-6 pill border border-ink-black bg-ink-black text-paper-white">
            <div className="eyebrow text-eclipse-green mb-2">Soulbound NFT — Creditcoin Testnet</div>
            <p className="font-ui text-sm leading-relaxed">
              <code className="font-label text-eclipse-green">CreditPassNFT.sol</code> — A non-transferable
              ERC721 that represents the borrower's credit passport. Minted on first verified repayment,
              updated on each subsequent verification. All transfer functions revert (soulbound). On-chain
              metadata includes score, tier, verified repayment count, and total verified amount as NFT traits.
            </p>
          </div>

          <div className="mb-6 p-6 pill border border-ink-black bg-paper-white">
            <div className="eyebrow text-muted-foreground mb-2">Frontend — Next.js + Tailwind CSS</div>
            <p className="font-ui text-sm leading-relaxed">
              Dashboard with credit score display, score tier badge, repayment history log, available loan
              terms, and the verification flow. Wagmi + Ethers.js for wallet connection and client-side
              transaction signing.
            </p>
          </div>
        </section>

        {/* 4. Attestcoin Protocol Integration */}
        <section className="mb-14">
          <h3 className="font-heading text-3xl font-light mb-4">04 — Attestcoin Protocol Integration</h3>
          <p className="font-ui text-base leading-relaxed mb-4">
            The Attestcoin Protocol is <strong>load-bearing</strong> — without it, there is no product.
            Every credit score update requires:
          </p>
          <ol className="font-ui text-base leading-relaxed space-y-2 ml-4 mb-4">
            <li>1. <strong>Cross-chain proof generation</strong> — Sepolia block headers and Merkle proofs are generated using the USC SDK (<code className="font-label">@gluwa/usc-sdk</code>).</li>
            <li>2. <strong>On-chain verification</strong> — The BlockProver precompile (<code className="font-label">0x0000000000000000000000000000000000000FD2</code>) validates the Sepolia block header and Merkle proof on Creditcoin.</li>
            <li>3. <strong>Transaction decoding</strong> — The verified transaction data is decoded to extract the borrower address and repayment amount.</li>
            <li>4. <strong>Score update</strong> — The CreditPass contract uses the decoded data to update the borrower's credit score, which the lending contract reads to determine loan terms.</li>
          </ol>
          <p className="font-ui text-base leading-relaxed">
            Verification completes in ~15 seconds (one Creditcoin block). Batch verification supports
            up to 10 queries, enabling importing multiple repayment histories at once. The CC3 Testnet
            supports Sepolia (chainkey 1) and Ethereum Mainnet (chainkey 3).
          </p>
        </section>

        {/* 5. Credit Scoring */}
        <section className="mb-14">
          <h3 className="font-heading text-3xl font-light mb-4">05 — Credit Scoring</h3>
          <p className="font-ui text-base leading-relaxed mb-4">
            The credit score is a simple linear formula:
          </p>
          <div className="mb-4 p-4 pill border border-ink-black bg-muted font-label text-sm">
            score += verified_repayment_amount × weight
          </div>
          <p className="font-ui text-base leading-relaxed mb-4">
            Score tiers determine loan terms:
          </p>
          <div className="space-y-2">
            <div className="flex items-center justify-between p-3 pill border border-ink-black">
              <span className="font-ui text-sm font-bold">0 — No History</span>
              <span className="font-label text-xs text-muted-foreground">20% APR · max 10 tCTC</span>
            </div>
            <div className="flex items-center justify-between p-3 pill border border-ink-black">
              <span className="font-ui text-sm font-bold">300+ — Limited</span>
              <span className="font-label text-xs text-muted-foreground">15% APR · max 50 tCTC</span>
            </div>
            <div className="flex items-center justify-between p-3 pill border border-ink-black bg-eclipse-green">
              <span className="font-ui text-sm font-bold">600+ — Verified Borrower</span>
              <span className="font-label text-xs">8% APR · max 100 tCTC</span>
            </div>
            <div className="flex items-center justify-between p-3 pill border border-ink-black">
              <span className="font-ui text-sm font-bold">800+ — Premium</span>
              <span className="font-label text-xs text-muted-foreground">5% APR · max 500 tCTC</span>
            </div>
          </div>
        </section>

        {/* 6. Soulbound NFT Passport */}
        <section className="mb-14">
          <h3 className="font-heading text-3xl font-light mb-4">06 — Soulbound NFT Passport</h3>
          <p className="font-ui text-base leading-relaxed mb-4">
            Each verified borrower receives a <strong>soulbound NFT</strong> — a non-transferable ERC721
            token that serves as their on-chain credit passport. The NFT is minted on the first verified
            repayment and its metadata is updated automatically on each subsequent verification.
          </p>
          <p className="font-ui text-base leading-relaxed mb-4">
            The NFT's on-chain metadata includes:
          </p>
          <ul className="font-ui text-base leading-relaxed space-y-1 ml-4 mb-4">
            <li>• <strong>Score</strong> — current credit score (0–950)</li>
            <li>• <strong>Tier</strong> — No History / Bronze / Silver / Gold / Platinum</li>
            <li>• <strong>Verified Repayments</strong> — count of cross-chain verified repayments</li>
            <li>• <strong>Total Verified Amount</strong> — cumulative verified repayment volume (in wei)</li>
          </ul>
          <p className="font-ui text-base leading-relaxed">
            Because the NFT is soulbound, it cannot be transferred or sold — it is permanently bound to
            the borrower's address. This prevents credit score fraud (buying someone else's reputation)
            and creates a portable, tamper-proof on-chain identity that other protocols can integrate with.
          </p>
        </section>

        {/* 7. Circular Flow */}
        <section className="mb-14">
          <h3 className="font-heading text-3xl font-light mb-4">07 — The Circular Flow</h3>
          <p className="font-ui text-base leading-relaxed">
            Repayments on Creditcoin can themselves be verified back on Ethereum — creating a circular
            credit-building loop. Each chain strengthens the borrower's position on the other. This
            transforms Creditcoin from a siloed chain into a <strong>cross-chain credit layer</strong>,
            where reputation flows freely between ecosystems.
          </p>
        </section>

        {/* 8. Why This Matters */}
        <section className="mb-14">
          <h3 className="font-heading text-3xl font-light mb-4">08 — Why This Matters</h3>
          <p className="font-ui text-base leading-relaxed mb-4">
            DeFi lending today is collateral-locked — you can only borrow against what you put up.
            CreditPass introduces <strong>reputation-based lending</strong> to cross-chain DeFi:
            borrow on Creditcoin backed by your repayment history on Ethereum.
          </p>
          <p className="font-ui text-base leading-relaxed">
            The Attestcoin Protocol makes this possible without oracles. The verification is
            mathematical — a smart contract proving something happened on another chain using only
            cryptographic proofs. This is the foundation of trustless cross-chain credit.
          </p>
        </section>

        {/* Footer */}
        <footer className="border-t border-ink-black pt-8 mt-16">
          <div className="flex items-center justify-between">
            <div>
              <div className="font-ui text-sm font-bold uppercase tracking-tight">CreditPass</div>
              <div className="font-label text-xs text-muted-foreground mt-1">
                Built for BUIDL CTC 2026 Fall · Creditcoin · Attestcoin Protocol
              </div>
            </div>
            <a
              href="/"
              className="font-ui text-sm uppercase tracking-[0.1em] px-4 py-2 pill-nav bg-ink-black text-paper-white hover:bg-eclipse-green hover:text-ink-black transition-colors"
            >
              Launch App →
            </a>
          </div>
        </footer>
      </main>
    </div>
  );
}
